#ifndef AY3891xRegisters_h
#define AY3891xRegisters_h

// AY38910 Registers
enum {
  PSG_REG_FREQ_A_LO = 0,
  PSG_REG_FREQ_A_HI,
  PSG_REG_FREQ_B_LO,
  PSG_REG_FREQ_B_HI,
  PSG_REG_FREQ_C_LO,
  PSG_REG_FREQ_C_HI,
  PSG_REG_FREQ_NOISE,
  PSG_REG_IO_MIXER,
  PSG_REG_LVL_A,
  PSG_REG_LVL_B,
  PSG_REG_LVL_C,
  PSG_REG_FREQ_ENV_LO,
  PSG_REG_FREQ_ENV_HI,
  PSG_REG_ENV_SHAPE,
  PSG_REG_IOA,
  PSG_REG_IOB,
  PSG_REG_TOTAL
};

#endif
